#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

nginx_cors_clear_origin() {
  declare desc="Clear custom Access-Control-Allow-Origin for a specific app"
  local cmd="nginx-cors:clear-origin"

  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  verify_app_name "$2"
  local APP="$2"

  if [[ -e "$DOKKU_ROOT/$APP/NGINX_CORS_ORIGIN" ]]; then
    dokku_log_info1 "Clearing custom NGINX CORS origin for $APP"
    rm -f "$DOKKU_ROOT/$APP/NGINX_CORS_ORIGIN"
  else
    dokku_log_info1 "No custom NGINX CORS origin configured for $APP"
  fi

  dokku_log_info1 "Restarting app $APP"
  dokku ps:restart "$APP"
}

nginx_cors_clear_origin "$@"
