#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"

nginx_cors_set_origin() {
  declare desc="Set Access-Control-Allow-Origin for a specific app"
  local cmd="nginx-cors:set-origin"

  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@

  verify_app_name "$2"
  local APP="$2"
  local ORIGIN="$3"

  if [[ -z "${ORIGIN:-}" ]]; then
    dokku_log_fail "Usage: dokku nginx-cors:set-origin <app> <origin>"
  fi

  dokku_log_info1 "Setting NGINX CORS origin for $APP to: $ORIGIN"
  printf '%s' "$ORIGIN" > "$DOKKU_ROOT/$APP/NGINX_CORS_ORIGIN"

  if [[ ! -e "$DOKKU_ROOT/$APP/NGINX_CORS" ]]; then
    dokku_log_info1 "NGINX CORS was not enabled for $APP; enabling now"
    touch "$DOKKU_ROOT/$APP/NGINX_CORS"
  fi

  dokku_log_info1 "Restarting app $APP"
  dokku ps:restart "$APP"
}

nginx_cors_set_origin "$@"
